Financial-Times/o-comments

- README.md
- main.scss
- src/stylesheets/_variables.scss
- src/stylesheets/livefyre_widget_overrides.scss
> suppress benton fonts

- src/javascripts/WidgetUi.js
See https://github.com/Financial-Times/o-comment-ui/pull/5
> Use agnostic templating

- origami.json
- src/stylesheets/_mixins.scss
- src/stylesheets/livefyre_widget_overrides.scss
We switched from scss-lint to sass-lint
> pass obt verify on v6

- README.md
Try and make it clear that we are currently working on a big replacement of the commenting platform. Hopefully if there us anyone planning to use this component they will speak to us first or if anyone plans to make changes to the component.
> Add a notice informing of upcoming changes

- bower.json
- src/js/stream.js
- src/scss/_mixins.scss
- test/scss/_mixins.test.scss
This will only be visible to the internal users.
> Display message to the user when using the staging environment

- src/js/stream.js
- src/js/utils/events.js
- test/methods/stream/publish-event.js
This will allow consumer apps to know when the user is required to login
and they will be able to handle directing the user to login.
> Add loginPrompt as a valid event

- main.scss
- src/js/utils/display-name.js
Make it look slightly prettier. This will be reviewed by a designer
later and updated.
> Add styling to the display name prompt

- main.scss
- src/scss/_mixins.scss
> Style display name to be like share article popup

- src/scss/coral-talk-iframe/main.scss
> Styling updates

- src/scss/coral-talk-iframe/main.scss
This isn't perfect because the comments wont be dark mode but at least
they will be readable. Also it doesn't look very elegant :(
> Make sure comments are readable in dark mode

- README.md
Section no longer exists, it was removed.
> Remove section from heading

- src/js/utils/events.js
This will allow us to see how often users are ignoring other users and
how often comments are reported.
> Track ignore user and report comment events

- src/scss/coral-talk-iframe/main.scss
We're still getting feedback that the font size is too small so we're
slightly increasing it again.
> Reduce the rem baseline to increase font size

- src/stylesheets/livefyre_widget_overrides.scss
We are closing old articles that use Livefyre to new comments.
> Close articles to new comments

- test/methods/stream/display-name-prompt.js
- test/stream.test.js
We never tested the `displayNamePrompt` function so here is my attempt. I was only able to partially test it because I had problems with race conditions and event listeners. To fully test it, I think we'd have to refactor the function.
> Add test to check if overlay is rendered

- src/scss/coral-talk-iframe/main.scss
I have also included some Origami upgrades that I must have missed last week when working on this.
> Fix the load more button appearing with a grey background

- src/javascripts/WidgetUi.js
> don't use mixed ESM and CJS

- README.md
> Document missing events in readme

- src/scss/coral-talk-iframe/main.scss
Coral Talk has released a new version that breaks styling. They have updated the compiled CSS for us. This commit applies those changes to the SASS.
> Update CSS that is rendered inside Coral iFrame

- README.md
> Update readme to conform to the readme linter

- src/js/comments.js
Fixes https://github.com/Financial-Times/o-comments/issues/27
> Log to console if any required configuration parameters are missing
