src/stylesheets/livefyre_widget_overrides.scss

Set a `min-width` on `.fyre-comment-flag-mobile-btn`.
The `.fyre-comment-flag-mobile-btn` class only appears on mobile devices, regardless of viewport width (mobile devices appear to be being served different markup)
The desktop site link actually contains the text 'report', so we set the width to `auto` so it is displayed at the correct width to contain its contents.
On mobile, we override the styles of this button using the `:before` pseudoelement so that says the word 'Report' rather than just being an icon (which it presumably is otherwise).
Because on mobile there's no real text in the button element itself, width auto shrinks it down too small. Setting a min-width on just the `.fyre-comment-flag-mobile-btn` class resolves this issue without affecting the desktop site
Before:
After:

Fix comments report button

---

src/stylesheets/livefyre_widget_overrides.scss

The submit button was flagged for having low color contrast in our recent a11y audit
We've replaced the two blues that make up the background of this button with slightly darker versions to bump contrast to 4.5:1 for both against the white text

increase button contrast

---

README.md
bower.json
demos/src/demo.mustache
demos/src/demo.scss
main.scss
src/stylesheets/_mixins.scss
src/stylesheets/_variables.scss
src/stylesheets/livefyre_widget_overrides.scss

Before
Now
This commit bumps to the new major of o-colors and the new major of
o-fonts.
Using metric instead of benton has meant bumping all of the type styles
by about 2px. This module should use o-typography ideally but there
are some wider design issues to be addressed with this component
so we're not moving to o-typography for now.

Bump colors and typography

---

src/stylesheets/livefyre_widget_overrides.scss

Reference to the renaming -- https://github.com/Financial-Times/fticons/blob/master/README.mdd#renamed

padlock was renamed to lock in fticon-v1

---

src/javascripts/utils.js

It seems with Android webview, `Storage` is defined, but `localStorage` is `null`, so errors are being thrown: https://sentry.io/nextftcom/ft-next-article/issues/579610508
This PR makes more use of `o-comment-utilities` [storage wrapper](https://github.com/Financial-Times/o-comment-utilities/blob/master/src/javascripts/storageWrapper/StorageWrapper.js#L6) to defend against this scenario.

More defensive access to localStorage

---

MIGRATION.md
README.md
bower.json

All other maintained components use ftdomdelegate, which is the
same except for the name. We don't want two versions included.
We can do this now @i-like-robots has removed the  "dom-delegate" 
name from ftdomdelegate and published to npm:
https://github.com/Financial-Times/ftdomdelegate/pull/93
_I've also removed resolutions: why is that there!?_
~I think it's acceptable to treat as a patch as the chance of conflict is 
extremely low. Thoughts?~ I take that back. This will have to be a major.

Switch dom-delegate for ftdomdelegate.

---

MIGRATION.md

This includes the old migration guide from v4 to v5 and a starting point
for all v6 changes.

Add a migration guide

---

.circleci/config.yml

This will allow prereleases to be published under the correct prerelease [dist-tag](https://docs.npmjs.com/cli/dist-tag)
Without this NPM will publish the changes as latest. See
https://github.com/npm/npm/issues/13248 for more info.
Prereleases are matched with the `^v[0-9]+\.[0-9]+\.[0-9]+-` regex which
will match any release with a pattern like `v1.0.0-beta.1`
Latest releases are matched with the `^v[0-9]+\.[0-9]+\.[0-9]+$` regex
which is stricter and forces the patch number to be the final character.
This will match release like `v12.0.3`

Add a NPM prerelease tag for beta releases

---

.circleci/config.yml

The previous `publish_prerelease_to_npm` regex did not correctly capture beta releases, so I've updated it so it will.

Update regex to capture beta releases

---

MIGRATION.md
README.md
src/js/comments.js
src/js/utils/events.js
test/oComments.test.js

Document deprecated events and events that are candidates for deprecation. See commit [f7a4870](https://github.com/Financial-Times/o-comments/commit/f7a4870b842f873238e7b98273fa7f171e4f157e) for details on why.
Also introduces a new event for when a comment is posted that doesn't pass the toxic automated moderation.

Add a toxic error event and document deprecated events

---

src/js/utils/auth/index.js
test/auth/auth.test.js

When there is no pseudonym found for a user, next-comments-auth-service /v1/jwt endpoint will respond with a 404 status code. In this case we still want to render the comments UI, but we don't want to allow users to comment until they define a Pseudonym.
This commit changes the behaviour of getJsonWebToken for the case when authentication service responds with 404. This will allow us to render the comments UI without a logged in user.

Do not throw when no jwt token is received

---

src/js/utils/auth/index.js
test/auth/auth.test.js

When a user has a valid session token, but no pseudonym assigned, `comments-auth-service` will respond with 205. In that case, we want to render Coral Talk with no authentication token, so that it can display an "Enter pseudonym" textbox.

Handle 205 response status from authentication service

---

src/js/comments.js
src/js/utils/auth/index.js
test/auth/auth.test.js

This is needed to display "Sign in to your FT account to comment" link when user is not signed in to their FT account in the Auth plugin.

Pass user sign-in status information to Coral

---

src/js/comments.js
src/js/utils/auth/index.js
test/auth/auth.test.js

comments-auth-service now has an endpoint that produces JWT tokens compatible with Coral V5. This PR makes use of that endpoint and feeds the JWT token when creating the embed script.

Get JWT token for Coral V5

---

src/js/comments.js

This was removed when we updates to Talk V5 as we wanted to just do the
minimum amount of work to get something visable.
Bringing this back will allow us to track events that are fired in Talk
from within our components and apps.

Reintroduce the dispatching of Talk events

---

MIGRATION.md
README.md
src/js/utils/events.js
test/oComments.test.js

Previously o-comments wasn't mentioned in the event naming because I had
only considered events being accessed via the `.on` method.
However events need to be accessible via event listeners as well and in
this case it would be nicer to include a namespacing.
This also includes some updates based on what events are accessible in
Talk v5

Rename events to work with event listeners

---

src/js/comments.js

This makes it easier to understand that parent is part of the window
object.

Add window to parent for clarity

---

src/js/utils/auth/index.js
test/auth/auth.test.js

We migrated the authentication features from `next-comments-auth-service` to `next-comments-api`. This PR makes o-comments to use the new API.

Use new authentication endpoint in comments-api

---

src/js/utils/auth/index.js
test/auth/auth.test.js

Display non-signed-in user experience when comments api `auth` endpoint responds with an error.
Currently, when comments-api auth endpoint responds with an error, comments are not rendered on the page at all. This creates confusion when testing the page.

Auth handle comments api error

---

demos/src/data/data.json

For some reason this article UUID doesn't work, maybe because it's super
old? I'm using a more recent UUID now.

Use a different article UUID

---

src/js/stream.js

Coral needs the parent element id as a parameter when initialising the embed script, otherwise, we get IntersectionObserver errors. Although we mostly have a static element id, in the apps we will have a dynamically generated element id because of the single page nature of the app. With this change, o-comments will always pass the correct element id to Coral.

Use parent element id when initializing Coral embed script

---

README.md
src/js/stream.js

The articles in the app may have different URLs than the ones in ft.com. This feature will enable app to pass a standard URL when initializing the comments component.

Use data-o-comments-story-url if available

---

demos/src/count.mustache
demos/src/data/data.json

The previous articleId returns null when calling the graphql api so I've
updated it to an articleId that actually returns a comment count.

Replace articleId

---

MIGRATION.md
README.md
src/js/utils/events.js
test/methods/stream/on.js

I wasn't aware when chosing these event names that event naming was part
of the Origami spec and I broke a bunch of rules.. bad Glynn.
https://origami.ft.com/spec/v1/javascript/#events

Update the event names to match Origami spec

---

src/js/comments.js
test/comments.test.js

When comments is initialised return the relevant class instance for
stream or count. This will allow consumers of comments to access methods
on of sub classes.

Expose the stream and count classes from comments

---

src/js/stream.js

Missed this in the previous PR that changes the environment to production.
The JWT token created for production environment is also valid for staging, but the display names can be different between the two environments. This change will ensure we get the correct display name on staging.

Pass staging parameter to auth endpoint

---

src/js/stream.js

renderComments promise should be resolved only when this.embed object is initialized.
In production, roughly 2 out of 10 times, this causes user not being able to sign in because by the time the JWT token promise resolves, renderComments promise is also resolved but this.embed is still undefined.

Fix intermittent issue of not being able to sign in

---

src/js/stream.js

We see a few external users in the Coral database. This means some people who aren't supposed to see the new Comments, which is behind a flag, are actually seeing it.
We want to track which app leaks the new Comments to the external users.

Pass source app option to jwt endpoint for tracking

---

src/js/utils/display-name.js

Rather than being vague about the validation we can call out the
characters that the user has used which are invalid.
Error messages for invalid characters will now follow this format
`The display name contains the following invalid characters: %$£^`

Improve error messages to mention invalid characters

---

src/js/stream.js

Allow us to separate old comment events from new comment events in our
dashboards.
This will make it easier to monitor the migration to Coral Talk

Add an identifier for new comment tracking events

---

src/js/utils/display-name.js

We are deprecating `https://comments-api.ft.com/user/displayname/:displayName` endpoint in favour of `https://comments-api.ft.com/displayname/isavailable/:displayName`.

Use the new display name validation endpoint

---

src/js/utils/display-name.js

When the display name doesn't contain any of the invalid characters, the value of variable `matchingCharacters` is `null`. This causes an error in the next line where we check the `length` of `matchingCharacters`.

Fixes a bug causing display name validation to fail silently

---

README.md
src/js/comments.js
test/comments.test.js

Exposing the Count.fetchCount method as `getCount` on the Comments
instance will allow consumers to just get the raw number without it
being applied to an element.

Expose the fetchCount method as getCount

---

src/js/stream.js

This is a bug that happens intermittently and causes a user to get "Sign in to comment" button even when the user is already signed in.
The cause of this bug is a race condition in the authentication mechanism. We are creating `this.embed` object and fetching the JWT token in parallel. When JWT fetch completes before the embed object is created, we call `this.embed.login` against an undefined object.

Fixes a bug that causes non-signed-in user experience

---

README.md
src/js/stream.js

I want to make sure the interface naming is consistent. This seems to be
something that slipped through and could be improved now before this is
released and requires a breaking change.

Replace "story" with "article" in the interface

---

src/js/utils/display-name.js

Coral Talk now doesn't impose validation rules on us, so we are free to
use the same rule set we use previously.
This means that all existing users shouldn't have an issue signing into
the new system.

Update display name chracter validation rules

---

src/scss/coral-talk-iframe/main.scss

When we brought this up to 19 it made the fonts a bit too small, this
should bring them back up to a sensible size.

Reduce the rem baseline in order to increase font size

---

src/scss/coral-talk-iframe/main.scss

I am very sorry that this exists but there was no other way to target that element 😢
Coral should be fixing this soon as its a bug and the button and text shouldn't ever appear but as a back up I am adding some css to hide it that makes me want to 🤮

Hide the not you sign out button with gross css

---

src/scss/coral-talk-iframe/main.scss

Fixes the bug that causes markdown formatted headings not to appear in the announcement box.
before:
after:

Fix styling bug in the announcement box

---

.circleci/config.yml
package.json
src/stylesheets/livefyre_widget_overrides.scss

We are going to be closing all the livefyre stories to new comments and interactions. Livefyre are able to do this for us for some functionality but are unable to prevent new likes or authentications. For this reason we are hiding this UI via css.
This will then be released as v5.1.2 and we will rebuild all our apps to use this version when we are ready.
I have checked with @JakeChampion and they are happy for the three commits made by @chee to be included in this release as they were in master previously but never released.

Hide livefyre functionality that we don't want to be visible after closing

---

main.scss
src/js/stream.js
src/scss/_mixins.scss
src/scss/coral-talk-iframe/main.scss
test/methods/stream/init.js
test/methods/stream/render-signed-in-message.js
test/stream.test.js

The "Signed in as" text was moved from inside the iFrame to above it. This will allow us to add an `edit` link beside the text for users to be able to change their display name. Currently, the functionality to edit a display name does not exist because we don't have control over what goes on inside the iFrame.
Before
After

Move "Signed in as" text above Coral iFrame

---

origami.json
src/js/stream.js
src/js/utils/purge-jwt-cache.js
test/methods/stream/authenticate-user.js
test/methods/stream/init.js
test/methods/stream/login.js
test/methods/stream/render-signed-in-message.js
test/stream.test.js

A user can now update their display name by clicking the edit link and filling out a form. This is a workaround because Coral doesn't support the ability to update a display name under the My Profile tab.

Edit display name

---

src/js/stream.js
src/js/utils/auth.js
test/methods/stream/authenticate-user.js
test/utils/auth.test.js

We don't need to track the source app for JWT token creation anymore and it makes purging JWT cache more complicated.

Remove sourceApp debug parameter

---

origami.json
src/js/stream.js
src/js/utils/auth.js
src/js/utils/purge-jwt-cache.js
test/methods/stream/authenticate-user.js
test/methods/stream/init.js
test/methods/stream/login.js
test/methods/stream/render-signed-in-message.js
test/stream.test.js
test/utils/auth.test.js

**NOTE**
We have released these changes under branch v6.2.0. This PR is created to get the same changes into master (i.e. v7.x.x).
A user can now update their display name by clicking the edit link and filling out a form. This is a workaround because Coral doesn't support the ability to update a display name under the My Profile tab.

Edit display name v7

---

src/js/stream.js
test/methods/stream/display-name-prompt.js
test/stream.test.js

This fixes an uncaught error that may happen after setting a display name for the first time.

Adds default value to function parameter (v6)

---

src/js/stream.js

This fixes an uncaught error that may happen after setting a display name for the first time.

Adds default value to function parameter

---

src/js/utils/events.js

The event names now match the event names that Coral consider to be
their public event names.
This is the minimum update to get the basic events changed and matches
the behaviour before they changed the event names.
We can still make further improvements to this to track the
auto-moderated comments and to make sure they are not tracked as
successful comments.
I suggest that we only merge this to master / v7 and don't worry about backwards support to v6 as we will be moving off v6 very soon and this doesn't need to be released straight away

Update event names to match Coral Talk new events

---

src/js/stream.js
src/js/utils/events.js
test/methods/stream/publish-event.js

Coral recently changed how events are emitted, see https://github.com/coralproject/talk/pull/2681#createComment, which broke the way we track toxic comment events. This PR fixes the event tracking.

Track toxic comment events

---

src/js/stream.js
src/js/utils/events.js
test/methods/stream/publish-event.js

Coral recently changed how events are emitted, see https://github.com/coralproject/talk/pull/2681#createComment, which broke the way we track toxic comment events. This PR fixes the event tracking in o-comments v7.

Track toxic comment event

---

src/js/stream.js

With the Origami major update, we started getting an error (o-overlay with id "displayName" already exists) when trying to reopen the display name prompt after once it has been closed.
Because there is no event named `oOverlay.close`, we are now listening to `oLayers.close` and when it is dispatched, we destroy the overlay.

Destroy display name prompt overlay when closed

---

src/js/stream.js

Submit and layer close events were firing multiple times when we reopen the display name prompt after closing it. 
This was mainly happening because we used to add an event listener to document for `oOverlay.ready` every time we prompt for display name.
We are now removing this event listeners when the display name pop-up is closed.
We suspect that this was causing performance issues in the app.

Remove event listeners after display name prompt overlay is closed

---

src/js/stream.js

Submit and layer close events were firing multiple times when we reopen the display name prompt after closing it. 
This was mainly happening because we used to add an event listener to document for `oOverlay.ready` every time we prompt for display name.
We are now removing this event listeners when the display name pop-up is closed.
We suspect that this was causing performance issues in the app.

v7 - Remove event listeners after display name prompt overlay is closed

---

src/js/stream.js

In the FT App, multiple instances of o-comments can be added to the document. Selecting the edit button via a class may not work in that case.
The app always sets a unique id to the o-comments and we make use of that id when giving an id to the edit button. Therefore we will have an edit button with a unique id in each instance of o-comments in the document.

Give edit button a unique id

---

src/js/stream.js
src/js/utils/events.js
test/methods/stream/publish-event.js

Comments that are flagged for moderation and later approved are
currently not being tracked. This means we are underreporting the
number of comments posted. The Data Team would rather we overreport by
tracking all comments that are flagged for moderation.

Track comments that are withheld for moderation

---

src/js/stream.js

In the FT App, multiple instances of o-comments can be added to the document. Selecting the edit button via a class may not work in that case.
The app always sets a unique id to the o-comments and we make use of that id when giving an id to the edit button. Therefore we will have an edit button with a unique id in each instance of o-comments in the document.

v7 - Give edit button a unique id

---

test/methods/stream/publish-event.js

This aims to stop unit tests interacting with each other by removing event listeners at the end of the tests.

Refactor publish event unit tests

---

src/js/count.js
test/count.test.js

The comment count link doesn't clearly indicate its destination or purpose to screen reader users. This PR adds an aria-label to make this more clear.
DAC Ticket: https://trello.com/c/xlaRxOIJ/161-link-purpose-issue-id-daclinkpurpose01

Add an aria-label to the comment count element

---

src/js/stream.js
src/js/utils/display-name.js
test/methods/stream/authenticate-user.js
test/methods/stream/init.js
test/utils/display-name.test.js

This will allow the display name to be passed into o-comments as an
option.
This will allow the parent application to set the display name in
advance should it exist. This will be useful for Longroom room where we
want the display name to be set in the user doesn't already have a
commenting account.
The display name that is passed in will need to pass the validation rules.
```
<div class="o-comments"
id="{element-id}"
data-o-component="o-comments"
data-o-comments-display-name="Test display name">
</div>
```

Add a display name option

---

src/scss/coral-talk-iframe/main.scss

When a user isn't signed in, only the Comments tab appears in the tab
bar. The tab looks like a button and it confuses users. This PR hides
the Comments tab when it's the only one in the bar.
Before:
After:

Hide the Comments tab bar if user isn't signed in

---

src/js/utils/events.js

I was stupidly mapping the wrong event names to our events. This would
mean that we were not tracking comment edits as we were only tracking
comment replies

Fixes a event naming mapping error

---

src/js/stream.js
src/js/utils/events.js
test/methods/stream/publish-event.js

Recently, we came across an issue where users were unable comment due to
some internal error on Coral's side. The issue was reported by different
users.
This PR allows us to track any errors and spot issues before it's
reported by users.

Track all errors thrown by Coral Talk

---

src/scss/coral-talk-iframe/main.scss

Increased indentation and a new left border style has been added for
comment replies to help users follow reply threads.
**Large screens (44px indents)**
**Medium screens (20px indents)**
**Small screens (20px indents + removed icons from comment action buttons)**

Increase the scan-ability of comment replies

---

src/scss/coral-talk-iframe/main.scss

In the IOS app the parent styles were slightly different and we ended up
with a border on all sides. We need to be explicit about removing the
border from the sides we don't want it on.

Removes the reply border from top, right & bottom

---

src/scss/coral-talk-iframe/main.scss

The links in the guidelines box failed the accessibility contrast check when using the standard link colour. This increases the darkness of the link text to pass accessibility checks.

Increase the contrast of guideline links

---

src/js/stream.js
src/scss/_mixins.scss

This improves the semantics of the mark up whilst also improving the
accessibility.
This will allow users to use keyboard navigation to get to the button
and then use the space or enter key to open the modal window.
**Before**
**After**

Switch edit display name link to be a button

---

src/js/utils/display-name.js

Addresses DAC_Label_in_Name_Issue2 - Voice activation users were unable to access some elements via their visible label. The label for the ‘Display name’ input wraps around the button and the input field. This is not marked up correctly and could cause issues for assistive technologies.
Solution: Remove wrapping of the label around other elements.
Also announces edit display name dialog error messages.

Edit display name dialog a11y

---

test/comments.test.js
test/methods/stream/publish-event.js
test/utils/display-name.test.js

If the error is not passed into `done` then mocha does not print out a useful stack trace of where the error originated from.

Improve error messages from async tests by passing the error to the `done` callback.

---

src/scss/coral-talk-iframe/main.scss

This fixes 3 issues that were introduced in the latest Coral release.
**Before**
**After**
Shown in the screenshots above, all the tabs are now the same height.
**Before**
I didn't get a screenshot of this as I tried to fix it quick and forgot - The icons below the comment for recommend, reply, share and flag were missing.
**After**

Style updates to improve styling based on Corals latest release (v6.3.2)

---

README.md
origami.json

The ci section was out of date and is not required.
The badge points to the old CI, this uses GitHub CI now.

remove the ci section from origami.json and circle badge from the readme

---

demos/src/demo.js
main.js
src/js/comments.js
src/js/stream.js
test/comments.test.js
test/count.test.js
test/methods/stream/authenticate-user.js
test/methods/stream/display-name-prompt.js
test/methods/stream/get-json-web-token.js
test/methods/stream/init.js
test/methods/stream/login.js
test/methods/stream/publish-event.js
test/methods/stream/render-comments.js
test/methods/stream/render-signed-in-message.js
test/stream.test.js
test/utils/auth.test.js
test/utils/display-name.test.js

relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing

add extension to relative imports to make the code work directly in a browser

---

src/scss/coral-talk-iframe/main.scss

The styles were conflicting with Coral's styles and producing a poor experience and accessibility
**Before**
**After**

Improve the styles for the reported state

---

src/js/stream.js
test/methods/stream/render-comments.js

Coral released a bad version of their embed.js script last week which broke commenting. They rolled it back shortly afterwards, but their script is set to be publicly cached for a week, and has no versioning in the URL we call it with. We're seeing new users still pick up the bad version and users still with broken comments after the original cache expiry date, so we're probably seeing cache chaining - adding a cachebuster seems the best way around that!
I've refactored the code a little bit to avoid defining base URLs multiple times. I've tested this version locally within the app and it appears to still load and function correctly!
Ideally I think it'd be nice to have a cachebuster that matches the o-comments version, but I don't think there's a nice way to do that...?
(I will also …

Add support for a cachebust query parameter to the base Coral embed script URL following a bad release by Coral

---

bower.json
src/js/stream.js
src/scss/_mixins.scss

This is the same issue as previously raised in #214 but adding the fix to v7 as well
The edit button next to the commenting display name didn't contain enough context for users of assistive tech
A visually hidden span has been added with the extra context needed to help all users understand the purpose of this button
This shows what it read out on voiceover when the edit button has focus
[CI-742](https://financialtimes.atlassian.net/browse/CI-742)

Accessibility fix: Add descriptive text to the edit display name button
